import { Fragment, useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { MapView, type MapViewHandle } from './components/MapView';
import { computeMovement, fetchField, runGatherer, runSynthesizer, searchPlaces } from './lib/api';
import { formatDistance } from './lib/geo';
import type { Anchor, Binding, CandidateField, CandidatePage, Coordinate, GathererOutput, ModelMeta, Movement, NearbyFieldSynthesis, RouteGeometry, SearchResult } from './lib/types';

const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));
type Phase = 'orientation' | 'preview' | 'discovering' | 'field' | 'gathering' | 'routing' | 'synthesizing' | 'complete' | 'error';
type FailureStage = 'field' | 'gatherer' | 'movement' | 'synthesizer' | null;
type LedgerState = { message: string; detail?: string };

function anchorFromResult(result: SearchResult): Anchor { return { label:result.label, coordinate:result.coordinate, source:'search', granularity:result.granularity, regionalContext:result.regionalContext }; }
function coordLabel(c: Coordinate) { return `${Math.abs(c.lat).toFixed(4)}°${c.lat>=0?'N':'S'} · ${Math.abs(c.lon).toFixed(4)}°${c.lon>=0?'E':'W'}`; }
function movementLabel(m: Movement|null) { if(!m)return ''; if(m.state==='NONE')return 'single place / no route'; if(m.state==='VERIFIED')return `trace / ${m.total_distance_m == null?'verified':formatDistance(Math.round(m.total_distance_m))}`; return `spatial relation / ${m.total_distance_m == null?'unverified':formatDistance(Math.round(m.total_distance_m))}`; }

function AnnotatedParagraph({result,activePlace,onHover,onPin}:{result:NearbyFieldSynthesis;activePlace:string|null;onHover:(id:string|null)=>void;onPin:(id:string)=>void}) {
  const spans = result.bindings.filter(b=>b.relation!=='structural'&&b.start!==null&&b.end!==null).sort((a,b)=>(a.start!-b.start!)||(a.end!-b.end!));
  const usable:Binding[]=[]; let end=0; for(const b of spans){if(b.start!>=end){usable.push(b);end=b.end!;}}
  const out:ReactNode[]=[]; let cursor=0;
  usable.forEach((b,i)=>{ if(b.start!>cursor)out.push(<Fragment key={`t${i}`}>{result.paragraph.slice(cursor,b.start!)}</Fragment>); out.push(<button key={`b${i}`} className={`prose-binding ${activePlace===b.place_id?'active':''}`} onMouseEnter={()=>onHover(b.place_id)} onMouseLeave={()=>onHover(null)} onFocus={()=>onHover(b.place_id)} onBlur={()=>onHover(null)} onClick={()=>onPin(b.place_id)}>{result.paragraph.slice(b.start!,b.end!)}</button>); cursor=b.end!; });
  if(cursor<result.paragraph.length)out.push(<Fragment key="tail">{result.paragraph.slice(cursor)}</Fragment>);
  const structuralActive=activePlace&&result.bindings.some(b=>b.place_id===activePlace&&b.relation==='structural');
  return <div className={`prose-object ${structuralActive?'structural-active':''}`}><p>{out}</p>{structuralActive&&<div className="structural-cue">structural relation · {activePlace}</div>}</div>;
}

export default function App() {
  const mapRef=useRef<MapViewHandle|null>(null); const searchController=useRef<AbortController|null>(null); const fieldController=useRef<AbortController|null>(null); const runController=useRef<AbortController|null>(null);
  const [phase,setPhase]=useState<Phase>('orientation'); const [failureStage,setFailureStage]=useState<FailureStage>(null);
  const [query,setQuery]=useState(''); const [results,setResults]=useState<SearchResult[]>([]); const [searching,setSearching]=useState(false); const [searchProvider,setSearchProvider]=useState<string|null>(null); const [searchError,setSearchError]=useState<string|null>(null);
  const [anchor,setAnchor]=useState<Anchor|null>(null); const [field,setField]=useState<CandidateField|null>(null); const [visibleRadius,setVisibleRadius]=useState<1000|3000|10000|null>(null); const [visibleCandidates,setVisibleCandidates]=useState<CandidatePage[]>([]);
  const [ledger,setLedger]=useState<LedgerState>({message:'find somewhere'}); const [pickMode,setPickMode]=useState(false); const [hoveredCandidate,setHoveredCandidate]=useState<string|null>(null); const [activeCandidate,setActiveCandidate]=useState<string|null>(null); const [activePlace,setActivePlace]=useState<string|null>(null); const [hoverPlace,setHoverPlace]=useState<string|null>(null); const [locationError,setLocationError]=useState<string|null>(null);
  const [runId,setRunId]=useState<string|null>(null); const [gatherer,setGatherer]=useState<GathererOutput|null>(null); const [movement,setMovement]=useState<Movement|null>(null); const [routeGeometry,setRouteGeometry]=useState<RouteGeometry|null>(null); const [synthesis,setSynthesis]=useState<NearbyFieldSynthesis|null>(null); const [gatherMeta,setGatherMeta]=useState<ModelMeta|null>(null); const [synthMeta,setSynthMeta]=useState<ModelMeta|null>(null); const [runError,setRunError]=useState<string|null>(null);

  const selectedCandidateIds=useMemo(()=>new Set(gatherer?.selected_places.map(p=>p.source_candidate_id)||[]),[gatherer]);
  const displayedPlace=hoverPlace||activePlace;
  const candidateFocus=useMemo(()=>{const id=activeCandidate||hoveredCandidate||(displayedPlace?gatherer?.selected_places.find(p=>p.place_id===displayedPlace)?.source_candidate_id:null);return field?.candidate_pages.find(c=>c.candidate_id===id)||null;},[activeCandidate,hoveredCandidate,displayedPlace,gatherer,field]);

  useEffect(()=>{ if(phase!=='orientation'||query.trim().length<2){setResults([]);setSearching(false);return;} const controller=new AbortController();searchController.current?.abort();searchController.current=controller;const timer=window.setTimeout(async()=>{setSearching(true);setSearchError(null);try{const data=await searchPlaces(query.trim(),controller.signal,mapRef.current?.getCenter());setResults(data.results);setSearchProvider(data.provider);}catch(error){if((error as Error).name!=='AbortError')setSearchError((error as Error).message);}finally{if(!controller.signal.aborted)setSearching(false);}},180);return()=>{window.clearTimeout(timer);controller.abort();};},[query,phase]);

  const previewAnchor=useCallback((next:Anchor)=>{setAnchor(next);setPhase('preview');setResults([]);setQuery(next.label||'');setLedger({message:'anchor preview',detail:next.label||coordLabel(next.coordinate)});mapRef.current?.preview(next.coordinate,next.granularity==='poi'||next.granularity==='address'?15:12.8);},[]);
  const handleMapPoint=(coordinate:Coordinate)=>{if(!pickMode||phase!=='orientation')return;setPickMode(false);previewAnchor({label:null,coordinate,source:'map_point',granularity:'map_point',regionalContext:{}});};
  const useLocation=()=>{if(!navigator.geolocation){setLocationError('Location is unavailable in this browser. Search instead.');return;}setLocationError(null);setLedger({message:'locating'});navigator.geolocation.getCurrentPosition(p=>previewAnchor({label:'Current location',coordinate:{lat:p.coords.latitude,lon:p.coords.longitude},source:'device_location',granularity:'device_location',regionalContext:{}}),()=>{setLocationError('Location permission was unavailable. Search or choose a map point instead.');setLedger({message:'find somewhere'});},{enableHighAccuracy:true,timeout:8000,maximumAge:30000});};

  const clearNarrative=()=>{runController.current?.abort();setRunId(null);setGatherer(null);setMovement(null);setRouteGeometry(null);setSynthesis(null);setGatherMeta(null);setSynthMeta(null);setRunError(null);setFailureStage(null);setActivePlace(null);};
  const cancelPreview=()=>{setPhase('orientation');setAnchor(null);setField(null);setVisibleRadius(null);setVisibleCandidates([]);setLedger({message:'find somewhere'});setActiveCandidate(null);clearNarrative();};

  const synthesize=async(data:CandidateField,g:GathererOutput,m:Movement,id:string,controller:AbortController)=>{setPhase('synthesizing');setFailureStage(null);setLedger({message:'writing',detail:'one paragraph · supplied evidence only'});try{const s=await runSynthesizer({run_id:id,field:data,gatherer:g,movement:m},controller.signal);if(controller.signal.aborted)return;setSynthesis(s.result);setSynthMeta(s.meta);setPhase('complete');setLedger({message:'work / complete',detail:movementLabel(m)});}catch(error){if((error as Error).name==='AbortError')return;setPhase('error');setFailureStage('synthesizer');setRunError((error as Error).message);setLedger({message:'writing unavailable',detail:'field, selection and movement preserved'});}};
  const route=async(data:CandidateField,g:GathererOutput,id:string,controller:AbortController)=>{setPhase('routing');setFailureStage(null);setLedger({message:'ordering',detail:'selected geographic places only'});try{const r=await computeMovement({anchor:{lat:data.anchor.lat,lon:data.anchor.lon},field:data,gatherer:g},controller.signal);if(controller.signal.aborted)return;setMovement(r.movement);setRouteGeometry(r.route_geometry);setLedger({message:r.movement.state==='VERIFIED'?'route verified':r.movement.state==='NONE'?'single place':'route unresolved',detail:r.movement.state==='RELATIONAL_UNVERIFIED'?'spatial ordering only · not a walking claim':movementLabel(r.movement)});await sleep(320);await synthesize(data,g,r.movement,id,controller);}catch(error){if((error as Error).name==='AbortError')return;setPhase('error');setFailureStage('movement');setRunError((error as Error).message);setLedger({message:'movement unavailable',detail:'field and selection preserved'});}};
  const gather=async(data:CandidateField)=>{runController.current?.abort();const controller=new AbortController();runController.current=controller;const id=crypto.randomUUID();setRunId(id);setGatherer(null);setMovement(null);setRouteGeometry(null);setSynthesis(null);setGatherMeta(null);setSynthMeta(null);setRunError(null);setActivePlace(null);setPhase('gathering');setFailureStage(null);setLedger({message:'selecting',detail:`${data.candidate_pages.length} bounded geographic candidates`});try{const g=await runGatherer({run_id:id,field:data,anchor_granularity:anchor?.granularity||'locality'},controller.signal);if(controller.signal.aborted)return;setGatherer(g.gatherer);setGatherMeta(g.meta);setLedger({message:`${g.gatherer.selected_places.length} ${g.gatherer.selected_places.length===1?'place':'places'} selected`,detail:'unselected field retained as context'});await sleep(360);await route(data,g.gatherer,id,controller);}catch(error){if((error as Error).name==='AbortError')return;setPhase('error');setFailureStage('gatherer');setRunError((error as Error).message);setLedger({message:'selection unavailable',detail:'geographic field preserved'});}};

  const confirmAnchor=async()=>{if(!anchor)return;fieldController.current?.abort();const controller=new AbortController();fieldController.current=controller;clearNarrative();setPhase('discovering');setField(null);setVisibleCandidates([]);setVisibleRadius(1000);setLedger({message:'field / 1 km',detail:'reading English Wikipedia geography'});try{const data=await fetchField(anchor,controller.signal);if(controller.signal.aborted)return;setField(data);const seq:(1000|3000|10000)[]=[1000];if(data.logical_radius_m>=3000)seq.push(3000);if(data.logical_radius_m>=10000)seq.push(10000);for(const radius of seq){if(controller.signal.aborted)return;setVisibleRadius(radius);const count=data.counts[String(radius) as '1000'|'3000'|'10000'];setVisibleCandidates(data.candidate_pages.filter(c=>c.distance_from_anchor_m<=radius));setLedger({message:radius===1000?'field / 1 km':`field widened / ${radius/1000} km`,detail:`${count} useful geographic ${count===1?'page':'pages'}`});await sleep(radius===data.logical_radius_m?420:650);}if(data.sparse){setLedger({message:'field sparse',detail:`${data.candidate_pages.length} geographic ${data.candidate_pages.length===1?'page':'pages'} within 10 km`});await sleep(420);setLedger({message:'reading local traces',detail:'non-geographic enrichment remains off-map'});await sleep(420);}setVisibleCandidates(data.candidate_pages);setVisibleRadius(data.logical_radius_m);setPhase('field');setLedger({message:data.sparse?'field / sparse':`field / ${data.logical_radius_m/1000} km`,detail:data.sparse?`${data.candidate_pages.length} geographic · ${data.enrichment.length} local ${data.enrichment.length===1?'reference':'references'}`:`${data.candidate_pages.length} geographic candidates retained`});await sleep(300);await gather(data);}catch(error){if((error as Error).name==='AbortError')return;setPhase('error');setFailureStage('field');setRunError((error as Error).message);setLedger({message:'field unavailable',detail:(error as Error).message});}};

  const retryStage=()=>{if(!field)return;if(failureStage==='gatherer'||failureStage==='movement')gather(field);else if(failureStage==='synthesizer'&&gatherer&&movement&&runId){const c=new AbortController();runController.current=c;synthesize(field,gatherer,movement,runId,c);}else if(failureStage==='field'&&anchor)confirmAnchor();};
  const again=()=>{if(field)gather(field);};
  const restart=()=>{fieldController.current?.abort();runController.current?.abort();setPhase('orientation');setAnchor(null);setField(null);setVisibleRadius(null);setVisibleCandidates([]);setActiveCandidate(null);setHoveredCandidate(null);setActivePlace(null);setHoverPlace(null);setQuery('');setPickMode(false);setLedger({message:'find somewhere'});clearNarrative();};
  const activateCandidate=(candidateId:string)=>{setActiveCandidate(v=>v===candidateId?null:candidateId);const p=gatherer?.selected_places.find(p=>p.source_candidate_id===candidateId);if(p)setActivePlace(v=>v===p.place_id?null:p.place_id);};
  const hoverCandidate=(candidateId:string|null)=>{setHoveredCandidate(candidateId);const p=candidateId?gatherer?.selected_places.find(p=>p.source_candidate_id===candidateId):null;setHoverPlace(p?.place_id||null);};
  const pinPlace=(placeId:string)=>setActivePlace(v=>v===placeId?null:placeId);

  const mapMode=phase==='orientation'||phase==='preview'?'orientation':'field';
  const processing=['discovering','gathering','routing','synthesizing'].includes(phase);
  const composite=phase==='complete';
  return <main className={`app phase-${phase}`}>
    <div className={`map-stage${composite?' composite':''}`}>
      <MapView ref={mapRef} mode={mapMode} anchor={anchor} radiusM={visibleRadius} candidates={visibleCandidates} selectedPlaces={gatherer?.selected_places||[]} movement={movement} routeGeometry={routeGeometry} activePlaceId={displayedPlace} pickMode={pickMode} settled={composite} onMapPoint={handleMapPoint} onCandidateHover={hoverCandidate} onCandidateActivate={activateCandidate}/>
      <header className="brand" aria-label="Nearby Field"><span className="brand-mark">NF</span><span className="brand-name">Nearby Field</span><span className="round-tag">R2</span></header>

      {phase==='orientation'&&<section className="orientation-controls" aria-label="Find a place"><div className="search-wrap"><label className="sr-only" htmlFor="place-search">Search for a place</label><input id="place-search" className="search-input" type="search" value={query} autoComplete="off" spellCheck={false} placeholder="Find a place" onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='ArrowDown')(document.querySelector('.search-result') as HTMLElement|null)?.focus();}}/><span className={`search-state ${searching?'active':''}`} aria-live="polite">{searching?'searching':''}</span></div>{(results.length>0||searchError||(!searching&&query.trim().length>=2&&results.length===0))&&<div className="search-results" role="listbox" aria-label="Place results">{results.map((r,i)=><button key={r.id} className="search-result" role="option" onClick={()=>previewAnchor(anchorFromResult(r))} onKeyDown={e=>{const bs=Array.from(document.querySelectorAll<HTMLButtonElement>('.search-result'));if(e.key==='ArrowDown'){e.preventDefault();bs[Math.min(i+1,bs.length-1)]?.focus();}if(e.key==='ArrowUp'){e.preventDefault();i===0?document.getElementById('place-search')?.focus():bs[i-1]?.focus();}}}><span className="result-primary">{r.label}</span><span className="result-secondary">{r.secondary||coordLabel(r.coordinate)}</span></button>)}{searchError&&<div className="search-error">{searchError}</div>}{!searchError&&!searching&&query.trim().length>=2&&results.length===0&&<div className="search-empty">Nothing surfaced here</div>}{searchProvider&&results.length>0&&searchProvider!=='nominatim'&&searchProvider!=='maptiler'&&<div className="provider-note">approximate matches · place-name index</div>}</div>}<div className="entry-actions"><button className="quiet-action" onClick={useLocation}>Use my location</button><button className={`quiet-action ${pickMode?'active':''}`} onClick={()=>setPickMode(v=>!v)}>{pickMode?'Cancel map pick':'Choose on map'}</button></div>{pickMode&&<div className="map-pick-dock"><span>Move the map until the crosshair is where you want, then choose the field below.</span></div>}{locationError&&<div className="location-error">{locationError}<button className="error-dismiss" onClick={()=>setLocationError(null)} aria-label="Dismiss">×</button></div>}</section>}

      {phase==='preview'&&anchor&&<section className="anchor-preview" aria-label="Confirm place"><span className="micro-label">anchor preview</span><h1>{anchor.label||'Map point'}</h1><p>{coordLabel(anchor.coordinate)}</p><div className="preview-actions"><button className="primary-action" onClick={confirmAnchor}>Use this place</button><button className="secondary-action" onClick={cancelPreview}>Back</button></div></section>}

      {phase!=='orientation'&&!composite&&<aside className="field-register" aria-live="polite"><div className="register-line"><span className={`register-pulse ${processing?'working':''}`}/>{ledger.message}</div>{processing&&<div className="stage-tracker">{['discovering','gathering','routing','synthesizing'].map((st,i)=>{const order=['discovering','gathering','routing','synthesizing'];const cur=order.indexOf(phase);const done=cur>i;const active=cur===i;return <span key={st} className={`stage-chip${done?' done':''}${active?' active':''}`}>{done?'✓':i+1} {st}</span>;})}</div>}{ledger.detail&&<div className="register-detail">{ledger.detail}</div>}</aside>}

      {field&&mapMode==='field'&&<section className="candidate-ledger" aria-label="Nearby Wikipedia candidates"><div className="ledger-head"><span>geographic field</span><span>{visibleCandidates.length.toString().padStart(2,'0')}</span></div><ol>{visibleCandidates.map(c=><li key={c.candidate_id}><button aria-pressed={selectedCandidateIds.has(c.candidate_id)} className={`${candidateFocus?.candidate_id===c.candidate_id?'candidate-row active':'candidate-row'} ${selectedCandidateIds.has(c.candidate_id)?'selected':''}`} onMouseEnter={()=>hoverCandidate(c.candidate_id)} onMouseLeave={()=>hoverCandidate(null)} onFocus={()=>hoverCandidate(c.candidate_id)} onBlur={()=>hoverCandidate(null)} onClick={()=>activateCandidate(c.candidate_id)}><span className="candidate-id">{c.candidate_id.slice(1)}</span><span className="candidate-title">{c.title}</span><span className="candidate-distance">{formatDistance(c.distance_from_anchor_m)}</span></button></li>)}</ol>{field.sparse&&<div className="sparse-register"><span>field sparse</span><span>{field.enrichment.length} local {field.enrichment.length===1?'reference':'references'} held off-map</span></div>}</section>}

      {candidateFocus&&<section className="candidate-inspector" aria-live="polite"><div className="inspector-meta">{candidateFocus.candidate_id} · {formatDistance(candidateFocus.distance_from_anchor_m)}{selectedCandidateIds.has(candidateFocus.candidate_id)?' · selected':''}</div><h2>{candidateFocus.title}</h2><p>{candidateFocus.extract}</p><a href={candidateFocus.url} target="_blank" rel="noreferrer">Wikipedia source ↗</a></section>}

      {phase==='error'&&<section className="error-surface" role="alert"><div className="micro-label">{failureStage||'run'} failure</div><p>{runError}</p><div className="preview-actions"><button className="primary-action" onClick={retryStage}>retry this stage</button><button className="secondary-action" onClick={restart}>new place</button></div></section>}

      {field?.sparse&&field.enrichment.length>0&&<details className="enrichment-register"><summary>local traces · {field.enrichment.length}</summary><div className="enrichment-body"><p className="enrichment-rule">These references have no map coordinate and are not route nodes.</p>{field.enrichment.map(x=><article key={x.source_id}><div>{x.source_id} · {x.title}</div><p>{x.snippet}</p></article>)}</div></details>}

      {field&&phase!=='complete'&&phase!=='error'&&<button className="new-place" onClick={restart}>new place</button>}
      <footer className="source-note">map © OpenFreeMap / OpenStreetMap · field: English Wikipedia</footer>
    </div>

    {composite&&synthesis&&<section className="reading-field" aria-label="Nearby Field paragraph">
      {movement&&<div className="movement-caption">{movementLabel(movement)}</div>}
      <AnnotatedParagraph result={synthesis} activePlace={displayedPlace} onHover={setHoverPlace} onPin={pinPlace}/>
      <div className="work-actions"><button className="primary-action" onClick={again}>again</button><button className="secondary-action" onClick={restart}>new place</button></div>
      {gatherer&&<details className="provenance-register"><summary>sources / run</summary><div className="provenance-body"><div><strong>{gatherer.selected_places.length}</strong> selected from {field?.candidate_pages.length||0} nearby Wikipedia pages</div><div>{movementLabel(movement)}</div>{gatherMeta&&<div>Gatherer · {gatherMeta.model} · {gatherMeta.attempts} {gatherMeta.attempts===1?'attempt':'attempts'}</div>}{synthMeta&&<div>Synthesizer · {synthMeta.model} · {synthMeta.attempts} {synthMeta.attempts===1?'attempt':'attempts'}</div>}<ul>{gatherer.selected_places.map(p=><li key={p.place_id}><a href={p.url} target="_blank" rel="noreferrer">{p.title}</a></li>)}</ul></div></details>}
    </section>}

    {field&&<div className="sr-only" aria-live="polite">Anchor: {field.anchor.label||coordLabel({lat:field.anchor.lat,lon:field.anchor.lon})}. {gatherer?`Selected places: ${gatherer.selected_places.map(p=>p.title).join(', ')}.`:''} {movement?.state==='VERIFIED'?`A pedestrian route connecting the selected places was verified${movement.total_distance_m?`, total distance ${Math.round(movement.total_distance_m)} metres`:''}.`:movement?.state==='RELATIONAL_UNVERIFIED'?'The selected places are ordered spatially, but a pedestrian route was not verified.':''} {synthesis?.paragraph||''}</div>}
  </main>;
}
