const params=new URLSearchParams(location.search);const fixture=params.get('fixture')||'harpers-ferry';const verified=params.get('route')==='verified';const $=s=>document.querySelector(s);const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const DATA={
 'harpers-ferry':{anchor:{label:'Harpers Ferry, West Virginia',lat:39.3234,lon:-77.732},radius:1000,sparse:false,candidates:[
  {id:'C01',place:'P01',title:'Harpers Ferry station',lat:39.32444,lon:-77.73111,d:139,url:'https://en.wikipedia.org/wiki/Harpers_Ferry_station'},
  {id:'C02',place:'P02',title:'Jefferson Rock',lat:39.322611,lon:-77.733278,d:141,url:'https://en.wikipedia.org/wiki/Jefferson_Rock'},
  {id:'C03',place:'P03',title:'Lockwood House (Harpers Ferry)',lat:39.32371,lon:-77.73549,d:302,url:'https://en.wikipedia.org/wiki/Lockwood_House_(Harpers_Ferry)'}],selected:['P01','P02','P03'],order:['P01','P02','P03'],paragraph:'Mara waited beside Harpers Ferry station with the box already retaped twice. At Jefferson Rock she set it down to press the split seam flat, then carried it uphill toward Lockwood House with one jar moved into her tote, where it knocked against her keys as she walked.',mentions:[['P01','Harpers Ferry station'],['P02','Jefferson Rock'],['P03','Lockwood House']]},
 taft:{anchor:{label:'Taft, Iran',lat:31.74944,lon:54.20889},radius:10000,sparse:true,candidates:[{id:'C01',place:'P01',title:'Taft, Iran',lat:31.74944,lon:54.20889,d:0,url:'https://en.wikipedia.org/wiki/Taft%2C_Iran'}],selected:['P01'],order:['P01'],paragraph:'Farideh’s mother had been asking her to stop at her aunt’s in Taft for three Thursdays, and each Thursday Farideh had driven back to Yazd with some small reason not to. This time her mother said only, “Bagh-e Golestan,” as if the neighbourhood itself could settle the matter, then added Sadri Garden because Farideh had once pretended not to know which place she meant. Farideh knew. When she reached Taft she slowed and kept going. Her aunt called before she had gone much farther. Farideh watched the name disappear from the screen, pulled over, and called her mother instead. “I’m here,” she said. Her mother asked, “At her house?” Farideh looked back the way she had come. “In Taft.” Neither of them spoke for a moment. Then Farideh put the car into gear and turned around.',mentions:[['P01','Taft']]}
};
const data=DATA[fixture]||DATA['harpers-ferry'];let active=null;const status=t=>{$('#status span').textContent=t};
function xy(c){const lons=data.candidates.map(x=>x.lon).concat(data.anchor.lon),lats=data.candidates.map(x=>x.lat).concat(data.anchor.lat);let minx=Math.min(...lons),maxx=Math.max(...lons),miny=Math.min(...lats),maxy=Math.max(...lats);if(maxx-minx<.002){minx-=.001;maxx+=.001}if(maxy-miny<.002){miny-=.001;maxy+=.001}return{x:28+(c.lon-minx)/(maxx-minx)*44,y:30+(maxy-c.lat)/(maxy-miny)*38};}
function setActive(id){active=active===id?null:id;document.querySelectorAll('[data-place]').forEach(el=>el.classList.toggle('active',!!active&&el.dataset.place===active));}
function renderPoints(selected=false){const box=$('#points');box.innerHTML='';for(const c of data.candidates){const p=xy(c),b=document.createElement('button');b.className='map-point'+(selected&&data.selected.includes(c.place)?' selected':'');b.style.left=p.x+'%';b.style.top=p.y+'%';b.dataset.place=c.place;b.setAttribute('aria-label',c.title+(selected&&data.selected.includes(c.place)?', selected':''));b.onclick=()=>setActive(c.place);b.onfocus=()=>setActive(c.place);b.onblur=()=>{active=null;document.querySelectorAll('[data-place]').forEach(el=>el.classList.remove('active'))};box.appendChild(b)}}
function renderLedger(selected=false){$('#ledger').innerHTML=`<h2>geographic field · ${String(data.candidates.length).padStart(2,'0')}</h2>${data.candidates.map(c=>`<button data-place="${c.place}" data-candidate="${c.id}" class="${selected&&data.selected.includes(c.place)?'selected':''}"><span class="id">${c.id.slice(1)}</span><span>${c.title}</span><span class="distance">${c.d<1000?c.d+' m':(c.d/1000).toFixed(1)+' km'}</span></button>`).join('')}${data.sparse?'<div class="sparse">field sparse · local enrichment remains off-map</div>':''}`;document.querySelectorAll('#ledger button').forEach(b=>{b.onclick=()=>setActive(b.dataset.place);b.onfocus=()=>setActive(b.dataset.place);b.onblur=()=>{active=null;document.querySelectorAll('[data-place]').forEach(el=>el.classList.remove('active'))}})}
function renderTrace(){const svg=$('#trace');svg.innerHTML='';if(data.order.length<2)return;const by=new Map(data.candidates.map(c=>[c.place,c]));const pts=data.order.map(id=>xy(by.get(id)));const pl=document.createElementNS('http://www.w3.org/2000/svg','polyline');pl.setAttribute('points',pts.map(p=>`${p.x/100*innerWidth},${p.y/100*innerHeight}`).join(' '));pl.setAttribute('class',verified?'relation verified':'relation');svg.appendChild(pl)}
function renderProse(){let text=data.paragraph,spans=[];for(const [place,needle] of data.mentions){const start=text.indexOf(needle);if(start>=0)spans.push({place,start,end:start+needle.length})}spans.sort((a,b)=>a.start-b.start);let html='',cursor=0;for(const s of spans){html+=escapeHtml(text.slice(cursor,s.start))+`<button data-place="${s.place}">${escapeHtml(text.slice(s.start,s.end))}</button>`;cursor=s.end}html+=escapeHtml(text.slice(cursor));$('#prose').innerHTML=`<p>${html}</p><div class="meta">${data.order.length===1?'single place / no route':verified?'verified pedestrian route fixture':'spatial relation / route not verified'}</div>`;$('#prose').hidden=false;document.querySelectorAll('#prose button').forEach(b=>{b.onclick=()=>setActive(b.dataset.place);b.onmouseenter=()=>setActive(b.dataset.place);b.onmouseleave=()=>{active=null;document.querySelectorAll('[data-place]').forEach(el=>el.classList.remove('active'))};b.onfocus=()=>setActive(b.dataset.place);b.onblur=()=>{active=null;document.querySelectorAll('[data-place]').forEach(el=>el.classList.remove('active'))}})}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function run(){renderPoints(false);renderLedger(false);status(data.radius===1000?'field / 1 km':'field / sparse');await sleep(120);status('selecting');await sleep(120);renderPoints(true);renderLedger(true);status(`${data.selected.length} ${data.selected.length===1?'place':'places'} selected`);await sleep(120);if(data.order.length>1){status(verified?'route verified':'route unresolved · spatial ordering only');renderTrace();await sleep(120)}else status('single place / no route');status('writing');await sleep(120);renderProse();status('work / complete');$('#sources').hidden=false;$('#sources div').innerHTML=data.candidates.map(c=>`<div><a href="${c.url}">${c.title}</a></div>`).join('');$('#sr').textContent=`Anchor ${data.anchor.label}. Selected places: ${data.candidates.filter(c=>data.selected.includes(c.place)).map(c=>c.title).join(', ')}. ${verified?'A pedestrian route fixture is shown.':'No pedestrian route is claimed.'} ${data.paragraph}`;document.body.dataset.nfReady='true';document.body.dataset.fixture=fixture;document.body.dataset.movement=data.order.length===1?'NONE':verified?'VERIFIED':'RELATIONAL_UNVERIFIED';window.__NF_R2_READY=true;}
run();
